// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKH1DiL5B-DQ3eMYfllhoWHVgGuybaviI',
    appId: '1:60453789113:web:e56e0b273b31b47ad4aa68',
    messagingSenderId: '60453789113',
    projectId: 'combustivel-2d1b3',
    authDomain: 'combustivel-2d1b3.firebaseapp.com',
    storageBucket: 'combustivel-2d1b3.firebasestorage.app',
    measurementId: 'G-E4PME09CEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Y-Wx-7UvoewSBQBGSmUqH6GCWDPUnig',
    appId: '1:60453789113:android:12e1b0df7a117a86d4aa68',
    messagingSenderId: '60453789113',
    projectId: 'combustivel-2d1b3',
    storageBucket: 'combustivel-2d1b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa8Zsp2uoqeJUu0RlbgKU6wvShCraq0XY',
    appId: '1:60453789113:ios:755c0a9b977a2cf1d4aa68',
    messagingSenderId: '60453789113',
    projectId: 'combustivel-2d1b3',
    storageBucket: 'combustivel-2d1b3.firebasestorage.app',
    iosBundleId: 'com.example.projetoAbastecimento',
  );

}